# Example pipeline.yaml configuration
start:
 - filter
 - format
 - output


error:
 - filter
 - output


warn:
 - filter
 - output


general:
 - output


# You can add more complex configurations like:
# start:
#   next:
#     - filter
#     - format
#     - output


